name: ci
defaults:
  run:
    shell: bash
on:
  push:
    branches:
    - main
    tags:
    - v*
jobs:
  build_image_and_test:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - run: echo "image=ghcr.io/go-tk/vk8s:${GITHUB_REF#refs/tags/}" >>"${GITHUB_ENV}"
    - uses: actions/checkout@v2
    - run: docker build --tag='${{ env.image }}' docker
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - run: go test ./...
    - run: docker push '${{ env.image }}'
  test:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - uses: actions/checkout@v2
    - run: go test ./...
