name: ci
defaults:
  run:
    shell: bash
on:
  push:
    branches:
    - main
    tags:
    - v*
jobs:
  build_and_test:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "image=ghcr.io/${{ github.repository }}:build-$(git log -1 --date=format:'%Y%m%d%H%M%S' --format='%ad')-$(git rev-parse HEAD | cut --bytes=1-12)" >>"${GITHUB_ENV}"
    - run: >-
        docker build
        --tag='${{ env.image }}'
        --label=org.opencontainers.image.created="$(date --rfc-3339=date)"
        --label=org.opencontainers.image.authors="$(git log -1 --pretty=format:'%an <%ae>')"
        --label=org.opencontainers.image.source="$(git remote get-url origin)"
        --label=org.opencontainers.image.revision="$(git rev-parse HEAD)"
        --label=org.opencontainers.image.ref.name='${{ env.image }}'
        docker
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - run: sed --regexp-extended --in-place 's|^(const image = ").*(")$|\1${{ env.image }}\2|' vk8s.go && go test ./...
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker push '${{ env.image }}'
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - run: |-
        curl
        -H 'Accept: application/vnd.github+json'
        -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
        -SsLf '${{ github.api_url }}/repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs?check_name=build_and_test'
        | jq --raw-output '.check_runs[-1].conclusion'
        | grep --line-regexp --fixed-strings 'success'
    - uses: actions/checkout@v2
    - run: |-
        echo "base_image=ghcr.io/${{ github.repository }}:build-$(git log -1 --date=format:'%Y%m%d%H%M%S' --format='%ad')-$(git rev-parse HEAD | cut --bytes=1-12)" >>"${GITHUB_ENV}"
        echo "image=ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}" >>"${GITHUB_ENV}"
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: >-
        docker pull '${{ env.base_image }}'
        && docker build
        --tag='${{ env.image }}'
        --label=org.opencontainers.image.created="$(date --rfc-3339=date)"
        --label=org.opencontainers.image.ref.name='${{ env.image }}'
        --label=org.opencontainers.image.base.digest="$(docker image inspect --format='{{index .RepoDigests 0}}' '${{ env.base_image }}' | cut --delimiter=@ --fields=2)"
        --label=org.opencontainers.image.base.name='${{ env.base_image }}'
        - <<<'FROM ${{ env.base_image }}'
        && docker push '${{ env.image }}'
